[project]
name = "toor-distance"
version = "0.1.0"
description = "Library to annotate for TOOR optimization."
authors = [
    {name = "Medtronic ICT"}
]
license = {text = "Proprietary"}
readme = "README.md"
requires-python = ">=3.13,<3.15"
dependencies = [
]

[tool.poetry.group.dev.dependencies]
jupyter = "^1.1.1"
ipykernel = "^7.2.0"
pylint = "^4.0.5"
flake8 = "^7.3.0"
isort = "^8.0.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
