[project]
name = "toor-distance"
version = "0.1.0"
description = "Library to annotate for TOOR optimization."
authors = [
    {name = "Medtronic ICT"}
]
license = {text = "Proprietary"}
readme = "README.md"
requires-python = "<=3.13"
dependencies = [
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
